name: Generate README.html

on: [push, pull_request]

jobs:
  doc_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Link checker
        uses: gaurav-nelson/github-action-markdown-link-check@v1

      - name: Content checker
        uses: gaurav-nelson/github-action-vale-lint@0.1.0

      - uses: docker://pandoc/core:2.9
        with:
          args: -o README.html README.md

